// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import database "github.com/jeevanrd/sms-service/database"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAccount provides a mock function with given fields: username, authId
func (_m *Repository) GetAccount(username string, authId string) (database.Account, error) {
	ret := _m.Called(username, authId)

	var r0 database.Account
	if rf, ok := ret.Get(0).(func(string, string) database.Account); ok {
		r0 = rf(username, authId)
	} else {
		r0 = ret.Get(0).(database.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, authId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPhoneNumber provides a mock function with given fields: accountId, number
func (_m *Repository) GetPhoneNumber(accountId int, number string) (database.PhoneNumber, error) {
	ret := _m.Called(accountId, number)

	var r0 database.PhoneNumber
	if rf, ok := ret.Get(0).(func(int, string) database.PhoneNumber); ok {
		r0 = rf(accountId, number)
	} else {
		r0 = ret.Get(0).(database.PhoneNumber)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(accountId, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
